setup:
  runner: train_dpdm_base
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  vae_model: 'CompVis/stable-diffusion-v1-4'
  sigma_data: 1
  use_vae: True
  set_w: True
data:
  path: /ds-sds/documents/iam_dataset/features/compvis_stable-diffusion-v1-4-64x256/train_features.msgpack
  split: train
  vocab_path: /ds-sds/documents/iam_dataset/tokenizer_vocab/
  name: iam_dataset
  num_channels: 4
  resolution_h: 8
  resolution_w: 32
  n_classes: 672
  one_hot: False
  fid_stats: 
  - fid_stats/iam_dataset/train.npz
  dataloader_params:
    num_workers: 1
    pin_memory: True
model:
  denoiser_name: edm
  denoiser_network: song
  ema_rate: .999
  network:
    image_size: 32
    num_in_channels: 4
    num_out_channels: 4
    label_dim: 672
    attn_resolutions:
    - 8
    - 16
optim:
  optimizer: Adam
  params:
    lr: 3e-4
    weight_decay: 0.
sampler:
  type: ddim
  stochastic: False
  num_steps: 50
  tmin: .002
  tmax: 80.
  rho: 7.
  guid_scale: 0.
  snapshot_batch_size: 8
  fid_batch_size: 8
  labels: null
train:
  seed: 0
  batch_size: 4096
  n_epochs: 300
  log_freq: 1
  snapshot_freq: 1000
  snapshot_threshold: 1
  save_freq: 1000
  save_threshold: 1
  fid_freq: 10000
  fid_samples: 5000
  fid_threshold: 1
loss: 
  version: v
  logsnr_min: -9.
  logsnr_max: 13.
  n_noise_samples: 8
  n_classes: 672
# loss: 
#   version: edm
#   p_mean: -1.2
#   p_std: 1.2
#   n_noise_samples: 8
#   n_classes: 672
dp:
  max_grad_norm: 1.
  delta: 8.671673112610347e-06
  epsilon: 10.0
  max_physical_batch_size: 256
  n_splits: 0